### ISSUE TITLE
Sangbog.zip

### ISSUE THREAD

**Issue by hrjakobsen** [f-klubben/sangbog#11]
Why does this repo contain `Sangbog.zip`? It seems to contain a bunch of songs, from places other than the F-klub.

**Comment by ScumbagDog** [comment]
Det er de forbudte tekster hvorpå sangbogen er baseret.

Dvs. Tågekammerets russangbog anno 2008-2010 fra AU, så vidt jeg lige kunne spotte mig til.

**Comment by ScumbagDog** [comment]
Ser ingen grund til at slette filen, så lader den bare være indtil videre
