### ISSUE TITLE
Jeg er på vej parody

### ISSUE THREAD

**Issue by JakobTopholt** [f-klubben/sangbog#42]
[Jeg er på vej (Fra "Bjørne Brødre"/Originalt Dansk Soundtrack) Lyrics](https://www.jiosaavn.com/lyrics/jeg-er-pa-vej-fra-bjorne-brodreoriginalt-dansk-soundtrack-lyrics/BSkZeURSRAs)

Sig til de andre at jeg har fejl.
Der' sqiggly lines at se.
Min kode er rød, nu commiter jeg
Og jeg glæder mig til et merge

or sometthing

**Comment by krestenlaust** [comment]
sjovt, men kan ikke helt få det til at passe 🤔  ellers et solidt sangvalg
